### ISSUE TITLE
Consider moving the .adf files into a folder

### ISSUE THREAD

**Issue by YesThatAllen** [SavingThrows/AdwareDefinitionFiles#11]
We'd like to propose the moving of all .adf files into folder(s) in the repo
### Benefits
- Ability to have more folders for known-good and testing, etc
  -  `AdwareDefinitionFiles` A current set of good definitions 
  -  `AdwareDefinitionFilesNeeded` 
  -  `AdwareDefinitionFilesTesting` 
  -  `AdwareDefinitionFilesEtc` 
  - There are already a number of stub adf files which have no useable data, they could be moved over.
- Less chances of including the `.git` in other solutions
- No more having to exclude the `README.MD`
### Downsides
- Unknown levels of pain in existing workflows which reference the current path

I looked in SavingThrow itself, and only found one issue, I proposed a fix for that.

Thoughts on the matter?

**Comment by sheagcraig** [comment]
That's pretty much it-users would have to update their configuration across all of their clients. Only one of those is included by default, but presumably, just about everyone using SavingThrow has all of them included.

I think having subfolders for non-production ready ones seems doable; I don't think it's a good idea to pull the rug out from under people who are already using them. If it were easy to do a redirect, then definitely, but I'm not sure whether that would even be possible since it's GitHub and not our own servers.

**Comment by YesThatAllen** [comment]
How many people are just pulling the entire folder now? 

how many wish there wasn't a `git` folder in the results, or that they could skip the testing .adf's which are there?

**Comment by sheagcraig** [comment]
So the way SavingThrow works is that each ADF file has to specified individually, so there's no problem with having to exclude the git folder or the readme. This is by design-I wanted to force Admins to have to go to the trouble of specifying exactly what they want and trust, rather than a blanket import.

Likewise, we continually have recommended that people fork this repo for their use; that way they're not getting definition updates by surprise-only when they `git pull upstream master`.

Despite this, I think a lot of people use the URL's to the definitions in this repo, so if they change, SavingThrow will just silently fail for them.

**Comment by YesThatAllen** [comment]
Gotcha.  Agreed that the cost-benefit isn't there at this time.

Perhaps we can revisit if/when there's a breaking change in SavingThrow that warrants a version bump.
